YOLOV6:
  WEIGHT: "./models/yolov6/yolov6l.pt"

  DATASET: ./detector/YOLOV6/data/coco.yaml
  IMG_SIZE: 640
  SCORE_THRESH: 0.35
  CONF_THRESH: 0.35 #0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
  HALF: False
